spring:
  application:
    name: discovery

server:
  port: 8761

eureka:
  #配置主机名
  instance:
    hostname: discovery
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 5
#    instance-id: ${seureka.instance.hostname}:${server.port}
  client:
    #该服务为注册中心，增加此行代表不在注册中心注册自己
    register-with-eureka: false
    #由于注册中心呢的职责是维护实例，为FALSE代表其不用去检索服务
    fetch-registry: false
    service-url:
      #代表注册到eureka服务端的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
